// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCB1G4RjvYAcUbXWFOU--U1sWdco6vOi4g',
    appId: '1:902208018284:web:4c7a11886de559b0c48549',
    messagingSenderId: '902208018284',
    projectId: 'agro-learning',
    authDomain: 'agro-learning.firebaseapp.com',
    storageBucket: 'agro-learning.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3KCr-hHZHBsZICQ5Vd4SBbs642pdVuFU',
    appId: '1:902208018284:android:958ee2a52a0c1b6dc48549',
    messagingSenderId: '902208018284',
    projectId: 'agro-learning',
    storageBucket: 'agro-learning.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSdGHbTNWaZhRAlv2lJWU6-RHibPqnpc0',
    appId: '1:902208018284:ios:d6c116ec016e0f14c48549',
    messagingSenderId: '902208018284',
    projectId: 'agro-learning',
    storageBucket: 'agro-learning.appspot.com',
    iosClientId: '902208018284-cgbia97njre3nkm2ehi6c2bj1q80c970.apps.googleusercontent.com',
    iosBundleId: 'com.example.agroLearning',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSdGHbTNWaZhRAlv2lJWU6-RHibPqnpc0',
    appId: '1:902208018284:ios:d6c116ec016e0f14c48549',
    messagingSenderId: '902208018284',
    projectId: 'agro-learning',
    storageBucket: 'agro-learning.appspot.com',
    iosClientId: '902208018284-cgbia97njre3nkm2ehi6c2bj1q80c970.apps.googleusercontent.com',
    iosBundleId: 'com.example.agroLearning',
  );
}
